app = 'back-make-books'
primary_region = 'syd'
console_command = '/rails/bin/rails console'

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'

[mounts]
source = "ogp_data"
destination = "/rails/public/ogp"

[env]
  RAILS_ENV = "production"
  PORT = "3000"

[deploy]
  release_command = "bundle exec rails db:migrate"
